services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ava-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017 # 👈 Backend talks to `mongo`
    depends_on:
      - mongo

  frontend:
    build:
      context: ./fnx-next-24
    container_name: ava-frontend
    volumes:
      - ./fnx-next-24:/app
      - /app/node_modules
    ports:
      - "80:3000"
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

  mongo:
    image: mongo
    container_name: ava-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: ava-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    depends_on:
      - mongo

volumes:
  mongo-data:
